### ISSUE TITLE
`NotImplementedError` error

### ISSUE THREAD

**Issue by BrunoQin** [mdhuggins/tensorflow-template#1]
Hello, it's a nice repo! But I meet some questions when I modify it to my own model.

```
    monitor = MonitorHook(10000, label="Training")  # Hacky way to get number of batches

    # Train the model
    classifier.train(
        input_fn=lambda: train_input_fn(8),
        hooks=[monitor]
    )

    monitor.cleanup()
```
I build up to two layers of ConvLSTM2D and make the model_factory, then determine the shape of inputs and outputs, finally I run the `train.py` but I meet following error in above code block:

```
Traceback (most recent call last):
  File ".\train\train.py", line 74, in <module>
    main()
  File ".\train\train.py", line 39, in main
    hooks=[monitor]
  File "C:\Users\Bruno\Anaconda3\envs\python36-cuda10.0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\Bruno\Anaconda3\envs\python36-cuda10.0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1160, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\Bruno\Anaconda3\envs\python36-cuda10.0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1190, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "C:\Users\Bruno\Anaconda3\envs\python36-cuda10.0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1148, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:\Users\Bruno\Anaconda3\envs\python36-cuda10.0\lib\site-packages\tensorflow_estimator\python\estimator\keras.py", line 288, in model_fn
    optimizer_config=optimizer_config)
  File "C:\Users\Bruno\Anaconda3\envs\python36-cuda10.0\lib\site-packages\tensorflow_estimator\python\estimator\keras.py", line 227, in _clone_and_build_model
    optimizer_config=optimizer_config)
  File "C:\Users\Bruno\Anaconda3\envs\python36-cuda10.0\lib\site-packages\tensorflow_core\python\keras\models.py", line 634, in clone_and_build_model
    clone = clone_model(model, input_tensors=input_tensors)
  File "C:\Users\Bruno\Anaconda3\envs\python36-cuda10.0\lib\site-packages\tensorflow_core\python\keras\models.py", line 422, in clone_model
    model, input_tensors=input_tensors, layer_fn=clone_function)
  File "C:\Users\Bruno\Anaconda3\envs\python36-cuda10.0\lib\site-packages\tensorflow_core\python\keras\models.py", line 191, in _clone_functional_model
    model, new_input_layers, layer_fn)
  File "C:\Users\Bruno\Anaconda3\envs\python36-cuda10.0\lib\site-packages\tensorflow_core\python\keras\models.py", line 241, in _clone_layers_and_model_config
    config = network.get_network_config(model, serialize_layer_fn=_copy_layer)
  File "C:\Users\Bruno\Anaconda3\envs\python36-cuda10.0\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1942, in get_network_config
    layer_config = serialize_layer_fn(layer)
  File "C:\Users\Bruno\Anaconda3\envs\python36-cuda10.0\lib\site-packages\tensorflow_core\python\keras\models.py", line 238, in _copy_layer
    created_layers[layer.name] = layer_fn(layer)
  File "C:\Users\Bruno\Anaconda3\envs\python36-cuda10.0\lib\site-packages\tensorflow_core\python\keras\models.py", line 56, in _clone_layer
    return layer.__class__.from_config(layer.get_config())
  File "C:\Users\Bruno\Anaconda3\envs\python36-cuda10.0\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 886, in get_config
    raise NotImplementedError
NotImplementedError
```

I check every file but I don't know where is wrong. I'm new to TensorFlow, can you fix this bug?

By the way, the template runs well.

**Comment by mdhuggins** [comment]
Could you share your model function? Also, what version of tensorflow are you using? (did you install from the requirements.txt?)

**Comment by BrunoQin** [comment]
Hi, I split the original `model_factory` into two files:
the first is `model.py`:

```
class MyModel(tf.keras.Model):
    def __init__(self, hidden_dim, output_dim):
        super(MyModel, self).__init__(name='my_model')
        self.hidden_dim = hidden_dim
        self.output_dim = output_dim
        self.layer1 = ConvLSTM2D(self.hidden_dim, kernel_size=(3, 3), activation='sigmoid', padding='same', return_sequences=True)
        self.layer2 = ConvLSTM2D(self.output_dim, kernel_size=(3, 3), activation='sigmoid', padding='same')

    def call(self, inputs):
        h1 = self.layer1(inputs)
        output = self.layer2(h1)
        return output
```

the second is `model_factory.py`:

```
def model_factory(height, width):

    inputs = tf.keras.Input(shape=(1,height, width,1))
    out = MyModel(1, 1)(inputs)
    model = tf.keras.Model(inputs=inputs, outputs=out)
    optimizer = tf.keras.optimizers.Adam(learning_rate=params.learning_rate)
    model.compile(loss='mse',
                  optimizer=optimizer,
                  metrics=['mse', 'mae'])

    return model
```
I use TensorFlow 2.0.0 higher than TensorFlow 2.0.0rc2 in requirements.txt

**Comment by mdhuggins** [comment]
It looks like the Tensorflow Estimator framework require's that layers in the keras model (from the model function) have model.get_config(). According to the Keras docs (https://keras.io/models/about-keras-models/) using a model subclass like you are results in get_config() being unavailable.

The solution (as recommended by Keras) is to use the to Keras functional API to make the model, without subclassing. This page might be helpful: https://keras.io/getting-started/functional-api-guide/

On a side note, are you used to using PyTorch?

**Comment by BrunoQin** [comment]
Thank you very much! I will try it tomorrow, I used Pytorch before and want to try tensorflow 2.0 this time :). But I am not very familiar with it.

**Comment by BrunoQin** [comment]
As your advice, I tried to combine my `model.py` and `model_factory.py` together, and it works finally. And I check `get_config` method in the above link and found that `get_config` is not available in subclassing. Thank you very much! I run my demo well!

**Comment by BrunoQin** [comment]
By the way, I found a very confusing problem when using this template: when building and training model, the template will use `model_to_estimator` method, and if I use such a method, the layers in model_factory may not accept extra input except in `input_fn`, for example, if I build a customize Keras Layer with an extra parameter which is a fixed matrix (tensor) and needs to be calculated before, I just pass it into `Layer.__init__` but it comes out:

```
Attempting to capture an EagerTensor without building a function.
```

So I change to train the model in eager mode with:

```
with tf.GradientTape() as tape:
```

in this way, it will be ok.
I don't know how to pass a matrix or pass a matrix need to be calculated out of graph into model. I try to add `@tf.function` on the func which is the calculating process, but it will produce new errors.

**Comment by mdhuggins** [comment]
@BrunoQin Thanks for the feedback! I actually ran into this same issue last week. It seems like the issue is specifically with adding an input for a fixed matrix without adding it in the input function. I've been looking for a nice solution, but for now my best answer is to include it in input.py
